"use client";

import React from "react";
import { selectSessionSummarySections } from "../../services/session/index.js";

export default function SessionSummaryPanel({ session, sourceLabel }) {
  const sections = selectSessionSummarySections(session);
  const isActive = session?.status === "active" || session?.status === "paused";

  return (
    <section className="rounded-2xl border border-white/10 bg-slate-950/40 p-5 shadow-2xl backdrop-blur-xl">
      <div className="mb-4 flex items-start justify-between gap-3">
        <div>
          <h2 className="text-sm font-bold uppercase tracking-wider text-white">
            {isActive ? "Provisional Session Summary" : "Overall Session Summary"}
          </h2>
          <p className="mt-1 text-xs text-slate-500">
            {isActive ? "This session is still in progress. Final structured summary is generated after ending the session." : "Structured summary generated by the session domain layer."}
          </p>
        </div>
        <span className="rounded-full border border-white/10 bg-slate-900 px-2 py-1 text-[10px] font-semibold text-slate-400">
          {sourceLabel}
        </span>
      </div>

      {sections.length === 0 ? (
        <div className="rounded-xl border border-dashed border-white/10 bg-slate-900/30 p-5 text-sm text-slate-400">
          {session ? "This session is still in progress. A reliable final summary will appear after the session is ended." : "No completed session summary is available yet."}
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-3 lg:grid-cols-5">
          {sections.map(({ key, fallbackTitle, section }) => (
            <article key={key} className="rounded-xl border border-white/10 bg-slate-900/45 p-4">
              <p className="text-[9px] font-bold uppercase tracking-[0.18em] text-slate-500">{fallbackTitle}</p>
              <h3 className="mt-2 text-sm font-bold text-white">{section.title}</h3>
              <p className="mt-2 text-xs leading-relaxed text-slate-400">{section.message}</p>
              <p className="mt-3 text-[10px] font-semibold uppercase tracking-wider text-cyan-300">Confidence: {section.confidence}</p>
            </article>
          ))}
        </div>
      )}
    </section>
  );
}
